# Code of Conduct {#code}

A _Code of Conduct_ is a set of basic ground rules that we ask participants in lab spaces to follow. The goal is to create an open and inclusive space for our work that helps us achieve our collective goals. Along with our lab culture/philosophy, it also provides a benchmark for self-evaluation and helps better define our identity as a community. 

<!-- Our code of conduct has been reviewed by the UNM EPS Dean's Office and by UNM Human Resources and office of Diversity, Equity, and Inclusion. -->

__We expect all lab members to adhere to the policies and guidelines outlined here.__  

<!-- Additional information and resources can be found in the [UNM EPS Code of Conduct and Diversity Statement](https://www.umassd.edu/media/umassdartmouth/UNM EPS/lab-pdf-files/UNM EPS---Code-of-conduct-and-diversitystatement_2.25.20-(1).docx).  -->


## Short version

The Markovich lab is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, age, race, or religion. We do not tolerate harassment of participants in any form and prioritize marginalized people’s safety over privileged people’s comfort.  

This code of conduct applies to all Markovich lab spaces, including group and individual meetings (face to face and remote), workshops, social events, email correspondence, and web channels and code repositories, both online and off. Anyone who violates this code of conduct may be sanctioned and referred to the university’s academic policies.
Some Markovich lab spaces may have additional rules in place, which will be made clearly available to participants. Participants are responsible for knowing and abiding by these rules.  

## Longer version

The Markovich lab is dedicated to providing a harassment-free experience for everyone. We do not tolerate harassment of group members or others in our larger communities in any form. Bullying is unwanted, aggressive behavior that involves a real or perceived power imbalance. 

This code of conduct applies to all Markovich lab spaces, including group and individual meetings (face to face and remote), workshops, social get togethers, email correspondence, and web channels and code repositories, both online and off. Anyone who violates this code of conduct may be sanctioned and referred to the School’s and university’s academic policies.  

Harassment includes:  

* Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, age, race, or religion.  
* Unwelcome comments regarding a person’s lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment.
* Deliberate misgendering or use of ‘dead’ or rejected names.
* Gratuitous or off-topic sexual images or behaviour in spaces where they’re not appropriate.
* Physical contact and simulated physical contact (eg, textual descriptions like “*hug*” or “*backrub*”) without consent or after a request to stop.
* Threats of violence.
* Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm.
* Deliberate intimidation.
* Stalking or following.
* Harassing photography or recording, including logging online activity for harassment purposes.
* Sustained disruption of discussion.
* Unwelcome sexual attention.
* Pattern of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others
* Continued one-on-one communication after requests to cease.
* Deliberate “outing” of any aspect of a person’s identity without their consent except as necessary to protect vulnerable people from intentional abuse.
* Publication of non-harassing private communication.  

The Markovich lab prioritizes marginalized people’s safety over privileged people’s comfort. The PI (Katie Markovich) reserves the right not to act on complaints regarding:  

* ‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’
* Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you.”
* Communicating in a ‘tone’ you don’t find congenial
* Criticizing racist, sexist, cissexist, or otherwise oppressive behavior or assumptions

### Reporting

If you are being harassed by a member of the Markovich lab, notice that someone else is being harassed, or have any other concerns, please contact the PI, Dr. Katie Markovich, at [kmarkovich@unm.edu](mailto:kmarkovich@unm.edu). If you do not wish to contact Dr. Markovich, please contact Department Chair Dr. Joe Galewsky [galewsky@unm.edu](mailto:galewsky@unm.edu) and/or UNM EPS Assistant Chair Dr. Lindsay Lowe-Worthington [lworthington@unm.edu](mailto:lworthington@unm.edu). If the person who is harassing you is on the team, they will recuse themselves from handling your incident. We will respond as promptly as we can.  

Lab members who believe they have been subjected to any kind of discrimination that conflicts with the University of New Mexico's policies and/or the laws of the state of New Mexico should seek assistance from a supervisor or an HR representative. [Information about the University of New Mexico's Equal Opportunity and Prohibited Discrimination policy can be found here](https://unmpolicy.policystat.com/policy/17084818/latest/).  

Additional resources on reporting and seeking training can be found on the [UNM Compliance, Ethics, and Equal Opportunity website](https://ceeo.unm.edu/).


__Confidentiality:__  Please remember that by way of his position at the university, Dr. Markovich is a mandated reporter under Title IX. This means that he is not allowed to keep matters falling under Title IX confidential, and is required to disclose these incidents to the administration. You are welcome to discuss matters with Dr. Markovich, but please keep this in mind when doing so. Gavin will do his best to remind you of his responsibilities at the start of conversations anticipated to relate to these topics. If you would prefer to discuss incidents of harassment that fall under Title IX with a confidential source, please refer to the [UNM CEEO website](https://ceeo.unm.edu/) or contact the [UNM Title IX office](mailto:titleix@unm.edu).  

This code of conduct applies to Markovich lab spaces, but if you are being harassed by a member of the Markovich lab or another member of the UNM community outside our spaces, we still want to know about it. We will take all good-faith reports of harassment by Markovich lab members seriously. This includes harassment outside our spaces and harassment that took place at any point in time. The abuse team reserves the right to exclude people from the Markovich lab based on their past behavior, including behavior outside Markovich lab spaces and behavior towards people who are not in the Markovich lab. The [University of New Mexico Counseling Assistance and Referral Services](https://cars.unm.edu/index.html) provides a range of services to help students develop improved coping skills to address emotional, interpersonal and academic concerns.  

### Consequences

Participants asked to stop any harassing behavior are expected to comply immediately.  

If a participant engages in harassing behavior, Dr. Markovich may take any action they deem appropriate, which includes referral to the Department Chair and Dean’s Office under the UNM EPS policy, and also including expulsion from all Markovich lab spaces.  

